In [32]:
# Change directory to level up to import functions
import os
os.chdir('..')

In [1]:
import pandas as pd

In [3]:
def get_season_string(season_start):
    """
    Generate a season string in the format YYYY-YY.

    Parameters
    ----------
    season_start : int
        The start year of the season. Must be a four-digit integer (e.g., 2023).

    Returns
    -------
    season_string : str
        The season string in the format "YYYY-YY".

    Raises
    ------
    ValueError
        If season_start is not a four-digit integer.
    """
    if not (isinstance(season_start, int) and len(str(season_start)) == 4):
        raise ValueError("season_start must be a four-digit integer (e.g., 2023).")

    season_end = season_start + 1
    season_end_string = str(season_end)[-2:]
    return f"{season_start}-{season_end_string}"

In [7]:
season_year

'2016-17'

In [22]:
season_start = 2016
if season_start <= 2018:
    encoding = "latin-1"
else:
    encoding = "utf-8"
season_year = get_season_string(season_start=season_start)
url = f'https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/{season_year}/players_raw.csv'
df = pd.read_csv(url, encoding=encoding)

### Get team data
teams_url = 'https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/master_team_list.csv'
df_teams = pd.read_csv(teams_url)

# ### Merge
# df_teams = df_teams[df_teams["season"] == season_year]
# df = df.merge(df_teams, on="team", how="left")

In [34]:

from src.tools.yaml_loader import load_yaml_file
# Load estimated team strengths for missing data
file_path_estimated_strength = "conf/estimated_team_strength.yaml"
estimated_team_strength = load_yaml_file(file_path_estimated_strength)

In [35]:
import requests

In [46]:
current_season='2019-20'
load_team_data(current_season,estimated_team_strength)

,name,strength,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away
0,Arsenal,4,1180,1240,1170,1170,1150,1200
1,Aston Villa,2,1020,1050,970,980,1000,1040
2,Bournemouth,2,1020,1020,990,1030,1000,1050
3,Brighton,2,1050,1010,1100,1100,1040,1030
4,Burnley,3,1110,1180,1130,1070,970,1110
5,Chelsea,4,1220,1230,1240,1240,1220,1250
6,Crystal Palace,3,1130,1120,1080,1180,1040,1040
7,Everton,3,1100,1240,1100,1210,1170,1180
8,Leicester,3,1210,1160,1150,1080,1210,1100
9,Liverpool,5,1340,1350,1310,1320,1310,1330
10,Man City,5,1330,1340,1260,1270,1320,1320
11,Man Utd,4,1220,1300,1260,1330,1180,1260
12,Newcastle,3,1090,1100,1030,1040,980,990
13,Norwich,2,980,1020,1030,1040,990,990
14,Sheffield Utd,3,1180,1200,1170,1180,1050,1110
15,Southampton,3,1150,1040,1080,1050,1110,1080
16,Spurs,4,1180,1240,1100,1130,1200,1140
17,Watford,3,1030,1140,1120,1120,1020,1150
18,West Ham,2,1040,1030,1000,1030,1030,1150
19,Wolves,4,1230,1190,1180,1230,1200,1200